language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install -qq python-numpy python-scipy

# command to install dependencies, we install numpy first cause its a pain
install:
  - python setup.py develop

# command to run tests, e.g. python setup.py test
script: python setup.py test
